development:
  adapter: postgresql
  database: chatty_development
  password: password
  host: localhost
  poor: 5

test:
  adapter: postgresql
  database: chatty_test
  password: password
  host: localhost
  poor: 5

production:
  adapter: postgresql
  database: chatty_production
  host: localhost
  poor: 5
